# Generated by Django 3.2 on 2022-07-23 09:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220723_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/default_profile_image', upload_to=core.models.get_profile_image_path),
        ),
    ]
