# Generated by Django 3.2 on 2022-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_itempost_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='location',
            field=models.CharField(default='punggol mrt', max_length=500),
            preserve_default=False,
        ),
    ]
