# Generated by Django 3.2 on 2022-07-27 04:48

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('pick_up_information', models.TextField(max_length=256)),
                ('location', models.CharField(max_length=500)),
                ('characteristics', models.TextField(blank=True, max_length=500, null=True)),
                ('soil_type', models.CharField(choices=[('None', 'None'), ('Chalk', 'Chalk'), ('Clay', 'Clay'), ('Peat', 'Peat'), ('Loam', 'Loam'), ('Sandy soil', 'Sandy Soil')], default='None', max_length=20)),
                ('light_requirement', models.CharField(choices=[('None', 'None'), ('Chalk', 'Chalk'), ('Clay', 'Clay'), ('Peat', 'Peat'), ('Loam', 'Loam'), ('Sandy soil', 'Sandy Soil')], default='None', max_length=20)),
                ('optimal_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Giveaway', 'Giveaway'), ('Lend', 'Lend'), ('Request', 'Request')], max_length=20)),
                ('item_type', models.CharField(choices=[('Seed/Plant', 'Seed Or Plant'), ('Fertilizer', 'Fertilizer'), ('Gardening tool', 'Gardening Tool'), ('Pot', 'Pot')], max_length=20)),
                ('days_to_harvest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water_requirement', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('Medium', 'Medium'), ('High', 'High'), ('Intensive', 'Intensive')], default='None', max_length=20)),
                ('growing_tips', models.TextField(blank=True, max_length=500, null=True)),
                ('cover_image', models.ImageField(upload_to=core.models.get_item_cover_image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
