# Generated by Django 3.2 on 2022-07-31 12:41

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_itempost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='cover_image',
            field=models.ImageField(storage=core.storage.OverwriteFileStorage(), upload_to=core.models.get_item_cover_image_path),
        ),
    ]
