# Generated by Django 3.2 on 2022-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_itempostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='light_requirement',
            field=models.CharField(choices=[('None', 'None'), ('Full sun', 'Full Sun'), ('Partial shade', 'Partial Shade'), ('Shade', 'Shade')], default='None', max_length=20),
        ),
    ]
