# Generated by Django 3.2 on 2022-07-27 07:49

import core.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_itempost_light_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempost',
            name='cover_image',
            field=models.ImageField(storage=core.storage.OverwriteFileStorage(), upload_to=core.models.get_item_cover_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.OverwriteFileStorage(), upload_to=core.models.get_profile_image_path),
        ),
    ]
