# Generated by Django 3.2 on 2022-08-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220803_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
    ]
