# Generated by Django 3.2 on 2022-08-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transaction_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_created',
            new_name='date_modified',
        ),
    ]
